version: '3.9'
x-defaults: &defaults
  env_file: .env
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  redis:
    <<: *defaults
    image: docker.io/library/redis:6
    command: "redis-server /etc/redis.conf"
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redis-datadir:/data
      - ./config/redis-Dev.conf:/etc/redis.conf
    networks:
      default:
        aliases:
          - redis
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          memory: 500M

volumes:
  redis-datadir:
    external: true
    name: redis-datadir

networks:
  default:
    external:
      name: trivialsec
